apiVersion: v2
appVersion: '1.0'
description: A Helm chart for adoption-web App
name: adoption-web
home: https://github.com/hmcts/adoption-web
version: 0.0.31
dependencies:
  - name: nodejs
    version: 2.4.14
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: idam-pr
    version: 2.3.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: idam-pr.enabled
