nodejs:
  image: 'hmctspublic.azurecr.io/adoption/web:latest'
  applicationPort: 3000
  readinessDelay: 130
  livenessDelay: 130
  autoscaling: # Default is false
    enabled: true
    maxReplicas: 5 # Required setting
    targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
  aadIdentityName: adoption
  ingressHost: adoption-web.{{ .Values.global.environment }}.platform.hmcts.net

  environment:
    NODE_ENV: production
    REFORM_TEAM: adoption
    REFORM_SERVICE_NAME: adoption-web

    SERVICE_AUTH_PROVIDER_URL: 'http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    IDAM_WEB_URL: 'https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login'
    IDAM_API_URL: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token'
    REDIS_HOST: 'adoption-web-session-storage-{{ .Values.global.environment }}.redis.cache.windows.net'
    REDIS_PORT: '6379'
    REDIS_TLS: 'true'
    SECURE_COOKIE: 'true'
    PAYMENTS_API_URL: 'http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    CCD_URL: 'http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    FEE_LOOKUP_URL: 'http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/fees-register/fees/lookup'
    EQUALITY_URL: 'https://pcq.{{ .Values.global.environment }}.platform.hmcts.net'
    DOCUMENT_MANAGEMENT_URL: 'http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    CDAM_API_URL: 'http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'

    #Pilot local-court email-Ids
    CHELMSFORD_FAMILY_COURT_EMAIL: 'chelmsfordadoptionapplication@mailinator.com'
    OXFORD_FAMILY_COURT_EMAIL: 'Oxfordadoptionapplication@mailinator.com'
    MEDWAY_FAMILY_COURT_EMAIL: 'Medwayadoptionapplication@mailinator.com'
    PORTSMOUTH_FAMILY_COURT_EMAIL: 'PortsmouthAdoptionApplication@mailinator.com'
    LEEDS_FAMILY_COURT_EMAIL: 'adoptionsleeds@mailinator.com'
    NORTHAMPTON_FAMILY_COURT_EMAIL: 'Northamptonadoptionapplications@mailinator.com'
    WORCESTER_FAMILY_COURT_EMAIL: 'Worcesteradoptionapplication@mailinator.com'
    NEWPORT_GWENT_FAMILY_COURT_EMAIL: 'NewportGwentadoptionapplication@mailinator.com'
    FALLBACK_EMAIL_ID_VALUE: 'adoptionproject@mailinator.com'
    IDAM_ROLE: 'adoption-citizen-user'

  keyVaults:
    adoption:
      secrets:
        - idam-secret
        - idam-system-user-name
        - idam-system-user-password
        - redis-access-key
        - s2s-secret
        - postcode-lookup-token
        - adoption-pcq-token
        - AppInsightsInstrumentationKey

idam-pr:
  enabled: false
