nodejs:
  image: 'hmctspublic.azurecr.io/adoption/web:latest'
  applicationPort: 3000
  aadIdentityName: adoption
  ingressHost: adoption-web.{{ .Values.global.environment }}.platform.hmcts.net

  environment:
    NODE_ENV: production
    RUNNING_ENV: '{{ .Values.global.environment }}'
    REFORM_TEAM: adoption
    REFORM_SERVICE_NAME: adoption-web
    REDIS_TTL_MS: 30
    SERVICE_AUTH_PROVIDER_URL: 'http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    IDAM_WEB_URL: 'https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login'
    IDAM_API_URL: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token'
    REDIS_HOST: 'adoption-web-session-storage-{{ .Values.global.environment }}.redis.cache.windows.net'
    SECURE_COOKIE: 'true'
    REDIS_PORT: 6380
    REDIS_TLS: true
    PAYMENTS_API_URL: 'http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    CCD_URL: 'http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    LOCATION_API_URL: 'http://rd-location-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    FEE_LOOKUP_URL: 'http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/fees-register/fees/lookup'
    EQUALITY_URL: 'https://pcq.{{ .Values.global.environment }}.platform.hmcts.net'
    DOCUMENT_MANAGEMENT_URL: 'http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    CDAM_API_URL: 'http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'

    #Pilot local-court email-Ids
    CHELMSFORD_FAMILY_COURT_EMAIL: 'chelmsfordadoptionapplication@mailinator.com'
    OXFORD_FAMILY_COURT_EMAIL: 'Oxfordadoptionapplication@mailinator.com'
    MEDWAY_FAMILY_COURT_EMAIL: 'Medwayadoptionapplication@mailinator.com'
    PORTSMOUTH_FAMILY_COURT_EMAIL: 'PortsmouthAdoptionApplication@mailinator.com'
    LEEDS_FAMILY_COURT_EMAIL: 'adoptionsleeds@mailinator.com'
    NORTHAMPTON_FAMILY_COURT_EMAIL: 'Northamptonadoptionapplications@mailinator.com'
    WORCESTER_FAMILY_COURT_EMAIL: 'Worcesteradoptionapplication@mailinator.com'
    NEWPORT_GWENT_FAMILY_COURT_EMAIL: 'NewportGwentadoptionapplication@mailinator.com'
    FALLBACK_EMAIL_ID_VALUE: 'adoptionproject@mailinator.com'
    IDAM_ROLE: 'citizen'
    COR_VAL: 'Cornwall Council'
    WOL_VAL: 'Wolverhampton City Council'
    SMC_VAL: 'Sandwell Metropolitan Council'
    TWB_VAL: 'Telford and Wrekin Borough Council'
    SHR_VAL: 'Shropshire Council'
    WAL_VAL: 'Walsall Borough Council'
    BCC_VAL: 'Bristol City Council'
    CMB_VAL: 'Cumbria County Council'
    BOL_VAL: 'Bolton Metropolitan Borough Council'
    HBC_VAL: 'Halton Borough Council'
    WIR_VAL: 'Wirral Borough Council'
    GTE_VAL: 'Gateshead Council'
    YCC_VAL: 'York City Council'
    BHC_VAL: 'Brighton and Hove City Council'
    TBC_VAL: 'Trafford Borough Council'
    DEV_VAL: 'Devon County Council'
    PEM_VAL: 'Pembrokeshire County Council'
    BNS_VAL: 'Bath & North East Somerset Council'
    GCC_VAL: 'Gloucestershire County Council'
    LBC_VAL: 'Luton Borough Council'
    NYS_VAL: 'North Yorkshire County Council'
    WIC_VAL: 'Wigan Council'
    PET_VAL: 'Peterborough City Council'
    SGL_VAL: 'South Gloucestershire Council'
    HAM_VAL: 'Hampshire County Council'
    VOG_VAL: 'Vale of Glamorgan Council'
    NPT_VAL: 'Neath & Port Talbot County Council'
    NTH_VAL: 'Northamptonshire County Council'
    CAR_VAL: 'Carmarthenshire County Council'
    GSCC_VAL: 'Surrey County Council'
    LBTH_VAL: 'London Borough of Tower Hamlets'
    BRD_VAL: 'Bridgend County Borough Council'
    SUF_VAL: 'Suffolk County Council'
    WRX_VAL: 'Wrexham County Borough Council'
    NFK_VAL: 'Norfolk County Council'
    NWT_VAL: 'Newport City Council'
    SHF_VAL: 'Sheffield City Council'
    ROT_VAL: 'Rotherham Metropolitan Borough Council'
    DON_VAL: 'City of Doncaster Council'
    BAR_VAL: 'Barnsley Metropolitan Borough Council'
    IOA_VAL: 'Isle of Anglesey County Council'
    KECH_VAL: 'Royal Borough of Kensington and Chelsea'
    WMS_VAL: 'Westminster City Council'
    DEN_VAL: 'Denbighshire County Council'
    CWC_VAL: 'Cheshire West and Chester Council'
    BRE_VAL: 'London Borough of Brent'
    CPY_VAL: 'Caerphilly County Borough Council'
    WAR_VAL: 'Warrington Borough Council'
    BGW_VAL: 'Blaenau Gwent County Borough Council'
    NHB_VAL: 'Northumberland County Council'
    STH_VAL: 'St Helens Borough Council'
    MON_VAL: 'Monmouthshire County Council'
    BRO_VAL: 'London Borough of Bromley'
    KKL_VAL: 'Kirklees Council'
    LEE_VAL: 'Leeds City Council'
    BED_VAL: 'Bedford Borough Council'
    FCC_VAL: 'Flintshire County Council'
    CON_VAL: 'Conwy County Borough Council'
    SBC_VAL: 'Sefton Borough Council'
    HRW_VAL: 'London Borough of Harrow'
    HPL_VAL: 'Hartlepool Borough Council'
    CBF_VAL: 'Central Bedfordshire Council'
    SWK_VAL: 'London Borough of Southwark'
    HUL_VAL: 'Hull City Council'
    BLA_VAL: 'Blackpool Borough Council'
    NTY_VAL: 'North Tyneside Council'
    KEN_VAL: 'Kent County Council'
    MCC_VAL: 'Manchester City Council'
    CAM_VAL: 'Cambridgeshire County Council'
    POW_VAL: 'Powys County Council'
    SUN_VAL: 'Sunderland City Council'
    IOW_VAL: 'Isle of Wight Council'
    BFO_VAL: 'Bracknell Forest Council'
    WBC_VAL: 'West Berkshire Council'
    SCF_VAL: 'Slough Children First'
    WIM_VAL: 'Royal Borough of Windsor & Maidenhead'
    WOK_VAL: 'Wokingham Borough Council'
    TCBC_VAL: 'Torfaen County Borough Council'
    KGN_VAL: 'London Borough of Kingston'
    RMD_VAL: 'London Borough of Richmond'
    WAD_VAL: 'London Borough of Wandsworth'
    GRW_VAL: 'Royal Borough of Greenwich'
    TOR_VAL: 'Torbay Council'
    PLY_VAL: 'Plymouth City Council'
    BRA_VAL: 'City of Bradford Metropolitan District Council'
    CAL_VAL: 'Calderdale MBC'
    RBC_VAL: 'Rochdale Borough Council'
    SAL_VAL: 'Salford City Council'
    ESX_VAL: 'East Sussex County Council'
    HAF_VAL: 'London Borough of Hammersmith and Fulham'
    REC_VAL: 'Redcar & Cleveland Borough Council'
    NTHW_VAL: 'West Northamptonshire Council'
    NTHN_VAL: 'North Northamptonshire Council'
    LAM_VAL: 'London Borough of Lambeth'
    ISL_VAL: 'London Borough of Islington'
    CDN_VAL: 'London Borough of Camden'
    LEW_VAL: 'London Borough of Lewisham'
    BNT_VAL: 'London Borough of Barnet'
    HLW_VAL: 'London Borough of Hounslow'
    WSX_VAL: 'West Sussex County Council'
    BAD_VAL: 'London Borough of Barking and Dagenham'
    ENF_VAL: 'London Borough of Enfield'
    WAF_VAL: 'London Borough of Waltham Forest'
    CRY_VAL: 'London Borough of Croydon'
    RED_VAL: 'London Borough of Redbridge'
    HAR_VAL: 'London Borough of Haringey'
    EAL_VAL: 'London Borough of Ealing'
    BEX_VAL: 'London Borough of Bexley'
    BUR_VAL: 'Bury Metropolitan Borough Council'
    ESS_VAL: 'Essex County Council'
    HAC_VAL: 'London Borough of Hackney'
    COL_VAL: 'City of London Corporation'
    HAV_VAL: 'London Borough of Havering'
    NEW_VAL: 'London Borough of Newham'
    RTL_VAL: 'Rutland County Council'
    #New-List
    STCC_VAL: 'Stoke on Trent County Council'
    SSCC_VAL: 'Staffordshire County Council'
    LCC_VAL: 'Leicester City Council'
    LCOC_VAL: 'Leicestershire County Council'
    LSCC_VAL: 'Lincolnshire County Council'
    NCC_VAL: 'Nottingham City Council'
    NSCC_VAL: 'Nottinghamshire County Council'
    DCC_VAL: 'Derby City Council'
    DCOC_VAL: 'Derby County Council'
    CCC_VAL: 'Coventry County Council'
    WCC_VAL: 'Warwickshire County Council'
    BCCO_VAL: 'Birmingham city council'
    SMBC_VAL: 'Solihull MBC'
    WSCC_VAL: 'Worcestershire County Council'
    HSCC_VAL: 'Herefordshire County Council'
    DMBC_VAL: 'Dudley MBC'
    PCC_VAL: 'Portsmouth City Council'
    SCC_VAL: 'Southampton City Council'
    WSC_VAL: 'Wiltshire Council'
    SBCO_VAL: 'Swindon Borough Council'
    SCCO_VAL: 'Somerset County Council'
    BCPC_VAL: 'Bournemouth, Christchurch & Poole council (BCP)'
    DCCO_VAL: 'Dorset County Council'
    LBH_VAL: 'London Borough Hillingdon'
    RBK_VAL: 'Royal Borough of Kingston'
    LBKT_VAL: 'London Borough Kingston upon Thames'
    LBS_VAL: 'London Borough of slough'
    COLO_VAL: 'City of London'
    LBSM_VAL: 'London Borough of Sutton & Merton'
    RBCO_VAL: 'Reading Borough Council'
    SBOC_VAL: 'Slough Borough Council'
    OSCC_VAL: 'Oxfordshire County Council'
    TBCO_VAL: 'Thurrock Borough Council'
    SOSBC_VAL: 'Southend-on-Sea Borough Council'
    HSCCO_VAL: 'Hertfordshire County Council'
    RCC_VAL: 'Rutland City Council'
    CCCO_VAL: 'Cambridge County Council'
    MEDC_VAL: 'Medway Council'
    MKC_VAL: 'Milton Keynes Council'
    BSCC_VAL: 'Buckinghamshire County Council'
    KUHCC_CAL: 'Kingston Upon Hull CC'
    ERY_VAL: 'East Riding Yorkshire C'
    NLSC_VAL: 'North Lincolnshire C'
    NELS_VAL: 'North East Lincolnshire'
    NCCC_VAL: 'Newcastle CC'
    STMBC_VAL: 'South Tyneside MBC'
    DBC_VAL: 'Darlington BC'
    DURCC_VAL: 'Durham CC'
    MBC_VAL: 'Middlesbrough BC'
    STBC_VAL: 'Stockton BC'
    WAK_VAL: 'Wakefield'
    LIV_VAL: 'Liverpool'
    KNO_VAL: 'Knowsley'
    CHE_VAL: 'Chesire East'
    CNW_VAL: 'Crewe & Nantwich'
    LSCCO_VAL: 'Lancashire County Council'
    BDBC_VAL: 'Blackburn with Darwen Borough Council'
    OLD_VAL: 'Oldham'
    STO_VAL: 'Stockport'
    TAM_VAL: 'Tameside'
    SWCC_VAL: 'Swansea CC'
    CER_VAL: 'Ceredigion'
    CARC_VAL: 'Cardiff Council'
    MTC_VAL: 'Merthyr Tydfil Council'
    SEWAS_VAL: 'South East Wales Adoption Service'
    RCT_VAL: 'Rhondda Cynon Taff'
    CYG_VAL: 'Cyngor Gwynedd'
    CSYM_VAL: 'Cyngor Sir Ynys Mon'
    GWC_VAL: 'Gwynedd Council'

    LIVERPOOL_FAMILY_COURT_EMAIL: 'Liverpooladoptionapplication@mailinator.com'
    CENTRAL_LONDON_FAMILY_COURT_EMAIL: 'cfc.onlineadoptions@mailinator.com'
    READING_FAMILY_COURT_EMAIL: 'Readingadoptionapplication@mailinator.com'
    SOCIAL_WORKER_SUPPORTED_DOMAINS:
      - gov.uk
      - pathfinderlegal.co.uk
      - nctrust.co.uk
      - birminghamchildrenstrust.co.uk
      - shropshire.cjsm.net
      - aspireadoption.co.uk
      - invicta.law
      - togetherforchildren.org.uk
      - dcstrust.co.uk
      - cumbriacs.cjsm.net
      - flintshire.nwalescls.com
      - conwy.nwalescls.com
      - gwynedd.llyw.cymru
      - brighterfuturesforchildren.org
      - achievingforchildren.org.uk
      - adoptioninmerseyside.co.uk
      - worcschildrenfirst.org.uk
      - aceadoption.com
      - adoptioninmerseyside.co.uk
      - adoptionconnects.co.uk
      - lgsslaw.co.uk
      - jigsawadoption.org.uk
      - scottishadoption.org
      - ccsadoption.org
      - adoptionwest.co.uk
      - ssafa.org.uk
      - adoptionmatters.org
      - caritascare.org.uk
      - stmargaretsadoption.org.uk
      - westernbayadoption.org
      - stdavidscs.org
      - scottishadoption.org
      - bradfordcft.org.uk
      - yorkshireadoptionagency.org.uk
      - adoptionlancashireblackpool.org.uk
      - adoptioncounts.org.uk
      - arcadoptionne.org.uk
      - coram.org.uk
      - barnardos.org.uk
      - adoptersforadoption.com
      - diagrama.org
      - sloughchildrenfirst.co.uk

    # Family Court List
    LEICESTER_VAL: 'Leicester County Court'
    STOKE-ON-TRENT_VAL: 'Stoke-on-Trent Combined Court'
    LINCOLN_VAL: 'Lincoln County Court and Family Court'
    NORTHAMPTON_VAL: 'Northampton Combined Court'
    NOTTINGHAM_VAL: 'Nottingham County Court and Family Court (and Crown)'
    DERBY_VAL: 'Derby Combined Court Centre'
    COVENTRY_VAL: 'Coventry Combined Court Centre'
    BIRMINGHAM_VAL: 'Birmingham Civil and Family Justice Centre'
    WORCESTER_VAL: 'Worcester Combined Court'
    WOLVERHAMPTON_VAL: 'Wolverhampton Combined Court Centre'
    PORTSMOUTH_VAL: 'Portsmouth Combined Court Centre'
    SWINDON_VAL: 'Swindon Combined Court'
    EXETER_VAL: 'Exeter Combined Court Centre'
    PLYMOUTH_VAL: 'Plymouth Combined Court'
    TAUNTON_VAL: 'Taunton Combined Court'
    TRURO_VAL: 'Truro Combined Court'
    BOURNEMOUTH_VAL: 'Bournemouth Combined Court'
    BRISTOL_VAL: 'Bristol Civil and Family Justice Centre'
    GLOUCESTERSHIRE_VAL: 'Gloucestershire Family and Civil Court'
    WEST-LONDON_VAL: 'West London Family Court'
    BARNET_VAL: 'Barnet Civil and Family Centre'
    BROMLEY_VAL: 'Bromley County Court and Family Court'
    CENTRAL_VAL: 'Central Family Court (First Avenue House)'
    CROYDON_VAL: 'Croydon Combined Court'
    EAST-LONDON_VAL: 'East London Family Court'
    LUTON_VAL: 'Luton Justice Centre'
    READING_VAL: 'Reading County Court and Family Court'
    OXFORD_VAL: 'Oxford Combined Court Centre'
    CHELMSFORD_VAL: 'Chelmsford County and Family Court'
    NORWICH_VAL: 'Norwich Combined Court Centre'
    WATFORD_VAL: 'Watford County Court and Family Court'
    PETERBOROUGH_VAL: 'Peterborough Combined Court Centre'
    BRIGHTON_VAL: 'Brighton County'
    GUILDFORD_VAL: 'Guildford Law Courts'
    MEDWAY_VAL: 'Medway County Court and Family Court'
    MILTON-KEYNES_VAL: 'Milton Keynes County Court and Family Court'
    KINGSTON-UPON-HULL_VAL: 'Kingston-upon-Hull Combined Court Centre'
    NEWCASTLE-UPON-TYNE_VAL: 'Newcastle upon Tyne Combined Court Centre'
    TEESSIDE_VAL: 'Teesside Combined Court Centre'
    YORK_VAL: 'York County Court and Family Court'
    LEEDS_VAL: 'Leeds Combined Court Centre'
    SHEFFIELD_VAL: 'Sheffield Combined Court Centre'
    LIVERPOOL_VAL: 'Liverpool Civil and Family Court'
    CHESTER_VAL: 'Chester Civil and Family Justice Centre'
    BARROW-IN-FURNESS_VAL: 'Barrow-in-Furness Magistrates and County Court'
    BLACKBURN_VAL: 'Blackburn Family Court'
    CARLISLE_VAL: 'Carlisle Combined Court'
    WEST-CUMBRIA_VAL: 'West Cumbria Courthouse'
    MANCHESTER_VAL: 'Manchester Civil Justice Centre (Civil and Family Courts)'
    ABERYSTWYTH_VAL: 'Aberystwyth Justice Centre'
    CAERNARFON_VAL: 'Caernarfon Justice Centre'
    CARDIFF_VAL: 'Cardiff Civil and Family Justice Centre'
    HAVERFORDWEST_VAL: 'Haverfordwest County and Family'
    LLANELLI_VAL: 'Llanelli Law Courts'
    NEWPORT_VAL: 'Newport (South Wales) County Court and Family Court'
    PONTYPRIDD_VAL: 'Pontypridd County Court and Family Court'
    PORT-TALBOT_VAL: 'Port Talbot Justice Centre'
    PRESTATYN_VAL: 'Prestatyn Justice Centre'
    SWANSEA_VAL: 'Swansea Civil Justice Centre'
    WREXHAM_VAL: 'Wrexham County & Family Court'
    #Local Court Email ID
    STOKE-ON-TRENT_FAMILY_COURT_EMAIL: 'stoke-on-trentadoptionapplication@mailinator.com'
    LEICESTER_FAMILY_COURT_EMAIL: 'leicesteradoptionapplication@mailinator.com'
    LINCOLN_FAMILY_COURT_EMAIL: 'lincolnadoptionapplication@mailinator.com'
    NOTTINGHAM_FAMILY_COURT_EMAIL: 'nottinghamadoptionapplication@mailinator.com'
    DERBY_FAMILY_COURT_EMAIL: 'derbyadoptionapplication@mailinator.com'
    COVENTRY_FAMILY_COURT_EMAIL: 'coventryadoptionapplication@mailinator.com'
    BIRMINGHAM_FAMILY_COURT_EMAIL: 'birminghamadoptionapplication@mailinator.com'
    WOLVERHAMPTON_FAMILY_COURT_EMAIL: 'wolverhamptonadoptionapplication@mailinator.com'
    SWINDON_FAMILY_COURT_EMAIL: 'swindonadoptionapplication@mailinator.com'
    EXETER_FAMILY_COURT_EMAIL: 'exeteradoptionapplication@mailinator.com'
    PLYMOUTH_FAMILY_COURT_EMAIL: 'plymouthadoptionapplication@mailinator.com'
    TAUNTON_FAMILY_COURT_EMAIL: 'tauntonadoptionapplication@mailinator.com'
    TRURO_FAMILY_COURT_EMAIL: 'truroadoptionapplication@mailinator.com'
    BOURNEMOUTH_FAMILY_COURT_EMAIL: 'bournemouthadoptionapplication@mailinator.com'
    BRISTOL_FAMILY_COURT_EMAIL: 'bristoladoptionapplication@mailinator.com'
    GLOUCESTERSHIRE_FAMILY_COURT_EMAIL: 'gloucestershireadoptionapplication@mailinator.com'
    WEST_LONDON_FAMILY_COURT_EMAIL: 'westlondonadoptionapplication@mailinator.com'
    BARNET_FAMILY_COURT_EMAIL: 'barnetadoptionapplication@mailinator.com'
    BROMLEY_FAMILY_COURT_EMAIL: 'bromleyadoptionapplication@mailinator.com'
    CENTRAL_FAMILY_COURT_EMAIL: 'centraladoptionapplication@mailinator.com'
    CROYDON_FAMILY_COURT_EMAIL: 'croydonadoptionapplication@mailinator.com'
    EAST_LONDON_FAMILY_COURT_EMAIL: 'east-londonadoptionapplication@mailinator.com'
    LUTON_FAMILY_COURT_EMAIL: 'lutonadoptionapplication@mailinator.com'
    NORWICH_FAMILY_COURT_EMAIL: 'norwichadoptionapplication@mailinator.com'
    WATFORD_FAMILY_COURT_EMAIL: 'watfordadoptionapplication@mailinator.com'
    PETERBOROUGH_FAMILY_COURT_EMAIL: 'peterboroughadoptionapplication@mailinator.com'
    BRIGHTON_FAMILY_COURT_EMAIL: 'brightonadoptionapplication@mailinator.com'
    GUILDFORD_FAMILY_COURT_EMAIL: 'guildfordadoptionapplication@mailinator.com'
    MILTON_KEYNES_FAMILY_COURT_EMAIL: 'milton-keynesadoptionapplication@mailinator.com'
    KINGSTON_UPON_HULL_FAMILY_COURT_EMAIL: 'kingston-upon-hulladoptionapplication@mailinator.com'
    NEWCASTLE_UPON_TYNE_FAMILY_COURT_EMAIL: 'newcastle-upon-tyneadoptionapplication@mailinator.com'
    TEESSIDE_FAMILY_COURT_EMAIL: 'teessideadoptionapplication@mailinator.com'
    YORK_FAMILY_COURT_EMAIL: 'yorkadoptionapplication@mailinator.com'
    SHEFFIELD_FAMILY_COURT_EMAIL: 'sheffieldadoptionapplication@mailinator.com'
    CHESTER_FAMILY_COURT_EMAIL: 'chesteradoptionapplication@mailinator.com'
    BARROW-IN-FURNESS_FAMILY_COURT_EMAIL: 'barrow-in-furnessadoptionapplication@mailinator.com'
    BLACKBURN_FAMILY_COURT_EMAIL: 'blackburnadoptionapplication@mailinator.com'
    CARLISLE_FAMILY_COURT_EMAIL: 'carlisleadoptionapplication@mailinator.com'
    WEST_CUMBRIA_FAMILY_COURT_EMAIL: 'west-cumbriaadoptionapplication@mailinator.com'
    MANCHESTER_FAMILY_COURT_EMAIL: 'manchesteradoptionapplication@mailinator.com'
    ABERYSTWYTH_FAMILY_COURT_EMAIL: 'aberystwythadoptionapplication@mailinator.com'
    CAERNARFON_FAMILY_COURT_EMAIL: 'caernarfonadoptionapplication@mailinator.com'
    CARDIFF_FAMILY_COURT_EMAIL: 'cardiffadoptionapplication@mailinator.com'
    HAVERFORDWEST_FAMILY_COURT_EMAIL: 'haverfordwestadoptionapplication@mailinator.com'
    LLANELLI_FAMILY_COURT_EMAIL: 'llanelliadoptionapplication@mailinator.com'
    PONTYPRIDD_FAMILY_COURT_EMAIL: 'pontypriddadoptionapplication@mailinator.com'
    PORT_TALBOT_FAMILY_COURT_EMAIL: 'port-talbotadoptionapplication@mailinator.com'
    PRESTATYN_FAMILY_COURT_EMAIL: 'prestatynadoptionapplication@mailinator.com'
    SWANSEA_FAMILY_COURT_EMAIL: 'swanseaadoptionapplication@mailinator.com'
    WREXHAM_FAMILY_COURT_EMAIL: 'wrexhamadoptionapplication@mailinator.com'

  keyVaults:
    adoption:
      secrets:
        - idam-secret
        - idam-system-user-name
        - idam-system-user-password
        - redis-access-key
        - s2s-secret
        - postcode-lookup-token
        - adoption-pcq-token
        - AppInsightsInstrumentationKey

idam-pr:
  enabled: false
