nodejs:
  image: 'hmctspublic.azurecr.io/adoption/web:latest'
  applicationPort: 3000
  memoryRequests: 512Mi
  cpuRequests: 1000m
  memoryLimits: 1524Mi
  cpuLimits: 2500m
  devmemoryRequests: 512Mi
  devcpuRequests: 1000m
  devmemoryLimits: 1524Mi
  devcpuLimits: 2500m
  readinessDelay: 130
  livenessDelay: 130
  autoscaling: # Default is false
    enabled: true
    maxReplicas: 5 # Required setting
    targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
  aadIdentityName: adoption
  ingressHost: adoption-web.{{ .Values.global.environment }}.platform.hmcts.net

  environment:
    NODE_ENV: production
    REFORM_TEAM: adoption
    REFORM_SERVICE_NAME: adoption-web

    SERVICE_AUTH_PROVIDER_URL: 'http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    IDAM_WEB_URL: 'https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login'
    IDAM_API_URL: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token'
    REDIS_HOST: 'adoption-web-session-storage-{{ .Values.global.environment }}.redis.cache.windows.net'

  keyVaults:
    adoption:
      secrets:
        - idam-secret
        - idam-system-user-name
        - idam-system-user-password
        - redis-access-key
        - s2s-secret
        - postcode-lookup-token
        #  - AppInsightsInstrumentationKey

idam-pr:
  enabled: false
