nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}
  devmemoryLimits: 1536Mi
  devmemoryRequests: 512Mi
  devcpuLimits: 500m
  devcpuRequests: 50m
  autoscaling:
    enabled: false
  environment:
    APPINSIGHTS_KEY: '00000000-0000-0000-0000-000000000000'
    PCQ_ENABLED: 'true'
    REDIS_TTL_MS: 30
    CCD_URL: 'http://ccd-data-store-api-aat.service.core-compute-aat.internal'
    IDAM_ROLE: 'citizen'
    CDAM_API_URL: 'http://ccd-case-document-am-api-aat.service.core-compute-aat.internal'
    # Family Court List
    LEICESTER_VAL: 'Leicester County Court'
    STOKE-ON-TRENT_VAL: 'Stoke-on-Trent Combined Court'
    LINCOLN_VAL: 'Lincoln County Court and Family Court'
    NORTHAMPTON_VAL: 'Northampton Combined Court'
    NOTTINGHAM_VAL: 'Nottingham County Court and Family Court (and Crown)'
    DERBY_VAL: 'Derby Combined Court Centre'
    COVENTRY_VAL: 'Coventry Combined Court Centre'
    BIRMINGHAM_VAL: 'Birmingham Civil and Family Justice Centre'
    WORCESTER_VAL: 'Worcester Combined Court'
    WOLVERHAMPTON_VAL: 'Wolverhampton Combined Court Centre'
    PORTSMOUTH_VAL: 'Portsmouth Combined Court Centre'
    SWINDON_VAL: 'Swindon Combined Court'
    EXETER_VAL: 'Exeter Combined Court Centre'
    PLYMOUTH_VAL: 'Plymouth Combined Court'
    TAUNTON_VAL: 'Taunton Combined Court'
    TRURO_VAL: 'Truro Combined Court'
    BOURNEMOUTH_VAL: 'Bournemouth Combined Court'
    BRISTOL_VAL: 'Bristol Civil and Family Justice Centre'
    GLOUCESTERSHIRE_VAL: 'Gloucestershire Family and Civil Court'
    WEST-LONDON_VAL: 'West London Family Court'
    BARNET_VAL: 'Barnet Civil and Family Centre'
    BROMLEY_VAL: 'Bromley County Court and Family Court'
    CENTRAL_VAL: 'Central Family Court (First Avenue House)'
    CROYDON_VAL: 'Croydon Combined Court'
    EAST-LONDON_VAL: 'East London Family Court'
    LUTON_VAL: 'Luton Justice Centre'
    READING_VAL: 'Reading County Court and Family Court'
    OXFORD_VAL: 'Oxford Combined Court Centre'
    CHELMSFORD_VAL: 'Chelmsford County and Family Court'
    NORWICH_VAL: 'Norwich Combined Court Centre'
    WATFORD_VAL: 'Watford County Court and Family Court'
    PETERBOROUGH_VAL: 'Peterborough Combined Court Centre'
    BRIGHTON_VAL: 'Brighton County'
    GUILDFORD_VAL: 'Guildford Law Courts'
    MEDWAY_VAL: 'Medway County Court and Family Court'
    MILTON-KEYNES_VAL: 'Milton Keynes County Court and Family Court'
    KINGSTON-UPON-HULL_VAL: 'Kingston-upon-Hull Combined Court Centre'
    NEWCASTLE-UPON-TYNE_VAL: 'Newcastle upon Tyne Combined Court Centre'
    TEESSIDE_VAL: 'Teesside Combined Court Centre'
    YORK_VAL: 'York County Court and Family Court'
    LEEDS_VAL: 'Leeds Combined Court Centre'
    SHEFFIELD_VAL: 'Sheffield Combined Court Centre'
    LIVERPOOL_VAL: 'Liverpool Civil and Family Court'
    CHESTER_VAL: 'Chester Civil and Family Justice Centre'
    BARROW-IN-FURNESS_VAL: 'Barrow-in-Furness Magistrates and County Court'
    BLACKBURN_VAL: 'Blackburn Family Court'
    CARLISLE_VAL: 'Carlisle Combined Court'
    WEST-CUMBRIA_VAL: 'West Cumbria Courthouse'
    MANCHESTER_VAL: 'Manchester Civil Justice Centre (Civil and Family Courts)'
    ABERYSTWYTH_VAL: 'Aberystwyth Justice Centre'
    CAERNARFON_VAL: 'Caernarfon Justice Centre'
    CARDIFF_VAL: 'Cardiff Civil and Family Justice Centre'
    HAVERFORDWEST_VAL: 'Haverfordwest County and Family'
    LLANELLI_VAL: 'Llanelli Law Courts'
    NEWPORT_VAL: 'Newport (South Wales) County Court and Family Court'
    PONTYPRIDD_VAL: 'Pontypridd County Court and Family Court'
    PORT-TALBOT_VAL: 'Port Talbot Justice Centre'
    PRESTATYN_VAL: 'Prestatyn Justice Centre'
    SWANSEA_VAL: 'Swansea Civil Justice Centre'
    WREXHAM_VAL: 'Wrexham County & Family Court'
    #Local Court Email ID
    STOKE-ON-TRENT_FAMILY_COURT_EMAIL: 'stoke-on-trentadoptionapplication@mailinator.com'
    LEICESTER_FAMILY_COURT_EMAIL: 'leicesteradoptionapplication@mailinator.com'
    LINCOLN_FAMILY_COURT_EMAIL: 'lincolnadoptionapplication@mailinator.com'
    NOTTINGHAM_FAMILY_COURT_EMAIL: 'nottinghamadoptionapplication@mailinator.com'
    DERBY_FAMILY_COURT_EMAIL: 'derbyadoptionapplication@mailinator.com'
    COVENTRY_FAMILY_COURT_EMAIL: 'coventryadoptionapplication@mailinator.com'
    BIRMINGHAM_FAMILY_COURT_EMAIL: 'birminghamadoptionapplication@mailinator.com'
    WOLVERHAMPTON_FAMILY_COURT_EMAIL: 'wolverhamptonadoptionapplication@mailinator.com'
    SWINDON_FAMILY_COURT_EMAIL: 'swindonadoptionapplication@mailinator.com'
    EXETER_FAMILY_COURT_EMAIL: 'exeteradoptionapplication@mailinator.com'
    PLYMOUTH_FAMILY_COURT_EMAIL: 'plymouthadoptionapplication@mailinator.com'
    TAUNTON_FAMILY_COURT_EMAIL: 'tauntonadoptionapplication@mailinator.com'
    TRURO_FAMILY_COURT_EMAIL: 'truroadoptionapplication@mailinator.com'
    BOURNEMOUTH_FAMILY_COURT_EMAIL: 'bournemouthadoptionapplication@mailinator.com'
    BRISTOL_FAMILY_COURT_EMAIL: 'bristoladoptionapplication@mailinator.com'
    GLOUCESTERSHIRE_FAMILY_COURT_EMAIL: 'gloucestershireadoptionapplication@mailinator.com'
    WEST_LONDON_FAMILY_COURT_EMAIL: 'westlondonadoptionapplication@mailinator.com'
    BARNET_FAMILY_COURT_EMAIL: 'barnetadoptionapplication@mailinator.com'
    BROMLEY_FAMILY_COURT_EMAIL: 'bromleyadoptionapplication@mailinator.com'
    CENTRAL_FAMILY_COURT_EMAIL: 'centraladoptionapplication@mailinator.com'
    CROYDON_FAMILY_COURT_EMAIL: 'croydonadoptionapplication@mailinator.com'
    EAST_LONDON_FAMILY_COURT_EMAIL: 'east-londonadoptionapplication@mailinator.com'
    LUTON_FAMILY_COURT_EMAIL: 'lutonadoptionapplication@mailinator.com'
    NORWICH_FAMILY_COURT_EMAIL: 'norwichadoptionapplication@mailinator.com'
    WATFORD_FAMILY_COURT_EMAIL: 'watfordadoptionapplication@mailinator.com'
    PETERBOROUGH_FAMILY_COURT_EMAIL: 'peterboroughadoptionapplication@mailinator.com'
    BRIGHTON_FAMILY_COURT_EMAIL: 'brightonadoptionapplication@mailinator.com'
    GUILDFORD_FAMILY_COURT_EMAIL: 'guildfordadoptionapplication@mailinator.com'
    MILTON_KEYNES_FAMILY_COURT_EMAIL: 'milton-keynesadoptionapplication@mailinator.com'
    KINGSTON_UPON_HULL_FAMILY_COURT_EMAIL: 'kingston-upon-hulladoptionapplication@mailinator.com'
    NEWCASTLE_UPON_TYNE_FAMILY_COURT_EMAIL: 'newcastle-upon-tyneadoptionapplication@mailinator.com'
    TEESSIDE_FAMILY_COURT_EMAIL: 'teessideadoptionapplication@mailinator.com'
    YORK_FAMILY_COURT_EMAIL: 'yorkadoptionapplication@mailinator.com'
    SHEFFIELD_FAMILY_COURT_EMAIL: 'sheffieldadoptionapplication@mailinator.com'
    CHESTER_FAMILY_COURT_EMAIL: 'chesteradoptionapplication@mailinator.com'
    BARROW-IN-FURNESS_FAMILY_COURT_EMAIL: 'barrow-in-furnessadoptionapplication@mailinator.com'
    BLACKBURN_FAMILY_COURT_EMAIL: 'blackburnadoptionapplication@mailinator.com'
    CARLISLE_FAMILY_COURT_EMAIL: 'carlisleadoptionapplication@mailinator.com'
    WEST_CUMBRIA_FAMILY_COURT_EMAIL: 'west-cumbriaadoptionapplication@mailinator.com'
    MANCHESTER_FAMILY_COURT_EMAIL: 'manchesteradoptionapplication@mailinator.com'
    ABERYSTWYTH_FAMILY_COURT_EMAIL: 'aberystwythadoptionapplication@mailinator.com'
    CAERNARFON_FAMILY_COURT_EMAIL: 'caernarfonadoptionapplication@mailinator.com'
    CARDIFF_FAMILY_COURT_EMAIL: 'cardiffadoptionapplication@mailinator.com'
    HAVERFORDWEST_FAMILY_COURT_EMAIL: 'haverfordwestadoptionapplication@mailinator.com'
    LLANELLI_FAMILY_COURT_EMAIL: 'llanelliadoptionapplication@mailinator.com'
    PONTYPRIDD_FAMILY_COURT_EMAIL: 'pontypriddadoptionapplication@mailinator.com'
    PORT_TALBOT_FAMILY_COURT_EMAIL: 'port-talbotadoptionapplication@mailinator.com'
    PRESTATYN_FAMILY_COURT_EMAIL: 'prestatynadoptionapplication@mailinator.com'
    SWANSEA_FAMILY_COURT_EMAIL: 'swanseaadoptionapplication@mailinator.com'
    WREXHAM_FAMILY_COURT_EMAIL: 'wrexhamadoptionapplication@mailinator.com'
    FALLBACK_EMAIL_ID_VALUE: 'adoptionproject@mailinator.com'
    # Notification Banner
    BANNER_ENABLED: 'false'
    BANNER_TITLE_TEXT_EN: 'Important'
    BANNER_TITLE_TEXT_CY: 'Pwysig'
    BANNER_MESSAGE_HTML_EN: 'Scheduled maintenance on 28th September 2024 from 8:00 AM to 9:00 AM. The service will be unavailable during this time.'
    BANNER_MESSAGE_HTML_CY: 'Cynhelir cynnal a chadw ar 28ain Medi 2024 rhwng 8:00 AM a 9:00 AM. Bydd y gwasanaeth ar gael yn ystod y cyfnod hwn.'

idam-pr:
  enabled: true
  redirect_uris:
    adoption-web:
      - https://${SERVICE_FQDN}/receiver
