security:
  referrerPolicy: 'origin'
port: 3000
timeout: 30000
services:
  authProvider:
    url: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal'
    microservice: 'adoption_web'
    secret: 'NEED TO INSERT SECRET'
  idam:
    authorizationURL: 'https://idam-web-public.aat.platform.hmcts.net/login'
    tokenURL: 'https://idam-api.aat.platform.hmcts.net/o/token'
    clientID: 'adoption-web'
    clientSecret: 'NEED TO INSERT SECRET'
    systemUsername: 'dummy_user'
    systemPassword: 'dummy_password'
  case:
    #url: 'http://ccd-data-store-api-adoption-cos-api-pr-84.service.core-compute-preview.internal'
    url: 'http://ccd-data-store-api-aat.service.core-compute-aat.internal'
  postcodeLookup:
    url: 'https://api.os.uk/search/places/v1'
    token: 'NEED TO INSERT SECRET'
  feeLookup:
    url: 'http://fees-register-api-aat.service.core-compute-aat.internal/fees-register/fees/lookup'
  documentManagement:
    url: http://dm-store-aat.service.core-compute-aat.internal
  payments:
    url: http://payment-api-aat.service.core-compute-aat.internal
  equalityAndDiversity:
    name: 'Equality and Diversity Service'
    url: 'https://pcq.aat.platform.hmcts.net'
    path: '/service-endpoint'
    port: 4000
    tokenKey: 'SERVICE_TOKEN_KEY'
    pcqEnabled: 'false'
health:
  timeout: 5000
  deadline: 15000
session:
  secret: 'local'
  redis:
    host:
    key:
e2e:
  userTestPassword: ''
appInsights:
  instrumentationKey:
