security:
  referrerPolicy: 'origin'
port: 3000
timeout: 30000
services:
  authProvider:
    url: ''
    microservice: 'adoption_web'
    secret: 'NEED TO INSERT SECRET'
  idam:
    authorizationURL: ''
    tokenURL: ''
    clientID: 'adoption-web'
    clientSecret: 'NEED TO INSERT SECRET'
    systemUsername: 'dummy_user'
    systemPassword: 'dummy_password'
    userRole: 'citizen'
  case:
    url: 'https://ccd-data-store-api-adoption-cos-api-pr-808.preview.platform.hmcts.net/'
  postcodeLookup:
    url: 'https://api.os.uk/search/places/v1'
    token: 'NEED TO INSERT SECRET'
  feeLookup:
    url: ''
  location_api:
    url: ''
  familyPublicLawCourt:
    code: 'ABA3'
  adoptionCourt:
    code: 'ABA4'
  documentManagement:
    url: ''
  cdam:
    url: ''
  payments:
    url: ''
  equalityAndDiversity:
    name: 'Equality and Diversity Service'
    url: ''
    path: '/service-endpoint'
    port: 4000
    tokenKey: 'SERVICE_TOKEN_KEY'
    pcqEnabled: 'false'
  pact:
    url: 'https://pact-broker.platform.hmcts.net'
    tag:
    pactDirectory: 'pact/pacts'
  draftStore:
    redis:
      host: 'localhost'
      port: 6379
      key:
      tls: false
      ttl: 30
health:
  timeout: 5000
  deadline: 15000
session:
  secret: 'local'
  redis:
    host:
    key:
  secureCookie: 'true'
e2e:
  userTestPassword: ''
appInsights:
  instrumentationKey:
localCourt:
  emailId:
    CHELMSFORD_FAMILY_COURT: 'chelmsfordadoptionapplication@mailinator.com'
    OXFORD_FAMILY_COURT: 'Oxfordadoptionapplication@mailinator.com'
    MEDWAY_FAMILY_COURT: 'Medwayadoptionapplication@mailinator.com'
    PORTSMOUTH_FAMILY_COURT: 'PortsmouthAdoptionApplication@mailinator.com'
    LEEDS_FAMILY_COURT: 'adoptionsleeds@mailinator.com'
    NORTHAMPTON_FAMILY_COURT: 'Northamptonadoptionapplications@mailinator.com'
    WORCESTER_FAMILY_COURT: 'Worcesteradoptionapplication@mailinator.com'
    NEWPORT_GWENT_FAMILY_COURT: 'NewportGwentadoptionapplication@mailinator.com'
    FALLBACK_EMAIL_ID: 'adoptionproject@mailinator.com'
    LIVERPOOL_FAMILY_COURT: 'Liverpooladoptionapplication@justice.gov.uk'
    CENTRAL_LONDON_FAMILY_COURT: 'cfc.onlineadoptions@justice.gov.uk'
    READING_FAMILY_COURT: 'Readingadoptionapplication@justice.gov.uk'
fpl:
  localAuthority:
    COR: 'Cornwall Council'
    WOL: 'Wolverhampton City Council'
    SMC: 'Sandwell Metropolitan Council'
    TWB: 'Telford and Wrekin Borough Council'
    SHR: 'Shropshire Council'
    WAL: 'Walsall Borough Council'
    BCC: 'Bristol City Council'
    CMB: 'Cumbria County Council'
    BOL: 'Bolton Metropolitan Borough Council'
    HBC: 'Halton Borough Council'
    WIR: 'Wirral Borough Council'
    GTE: 'Gateshead Council'
    YCC: 'York City Council'
    BHC: 'Brighton and Hove City Council'
    TBC: 'Trafford Borough Council'
    DEV: 'Devon County Council'
    PEM: 'Pembrokeshire County Council'
    BNS: 'Bath & North East Somerset Council'
    GCC: 'Gloucestershire County Council'
    LBC: 'Luton Borough Council'
    NYS: 'North Yorkshire County Council'
    WIC: 'Wigan Council'
    PET: 'Peterborough City Council'
    SGL: 'South Gloucestershire Council'
    HAM: 'Hampshire County Council'
    VOG: 'Vale of Glamorgan Council'
    NPT: 'Neath & Port Talbot County Council'
    NTH: 'Northamptonshire County Council'
    CAR: 'Carmarthenshire County Council'
    GSCC: 'Surrey County Council'
    LBTH: 'London Borough of Tower Hamlets'
    BRD: 'Bridgend County Borough Council'
    SUF: 'Suffolk County Council'
    WRX: 'Wrexham County Borough Council'
    NFK: 'Norfolk County Council'
    NWT: 'Newport City Council'
    SHF: 'Sheffield City Council'
    ROT: 'Rotherham Metropolitan Borough Council'
    DON: 'City of Doncaster Council'
    BAR: 'Barnsley Metropolitan Borough Council'
    IOA: 'Isle of Anglesey County Council'
    KECH: 'Royal Borough of Kensington and Chelsea'
    WMS: 'Westminster City Council'
    DEN: 'Denbighshire County Council'
    CWC: 'Cheshire West and Chester Council'
    BRE: 'London Borough of Brent'
    CPY: 'Caerphilly County Borough Council'
    WAR: 'Warrington Borough Council'
    BGW: 'Blaenau Gwent County Borough Council'
    NHB: 'Northumberland County Council'
    STH: 'St Helens Borough Council'
    MON: 'Monmouthshire County Council'
    BRO: 'London Borough of Bromley'
    KKL: 'Kirklees Council'
    LEE: 'Leeds City Council'
    BED: 'Bedford Borough Council'
    FCC: 'Flintshire County Council'
    CON: 'Conwy County Borough Council'
    SBC: 'Sefton Borough Council'
    HRW: 'London Borough of Harrow'
    HPL: 'Hartlepool Borough Council'
    CBF: 'Central Bedfordshire Council'
    SWK: 'London Borough of Southwark'
    HUL: 'Hull City Council'
    BLA: 'Blackpool Borough Council'
    NTY: 'North Tyneside Council'
    KEN: 'Kent County Council'
    MCC: 'Manchester City Council'
    CAM: 'Cambridgeshire County Council'
    POW: 'Powys County Council'
    SUN: 'Sunderland City Council'
    IOW: 'Isle of Wight Council'
    BFO: 'Bracknell Forest Council'
    WBC: 'West Berkshire Council'
    SCF: 'Slough Children First'
    WIM: 'Royal Borough of Windsor & Maidenhead'
    WOK: 'Wokingham Borough Council'
    TCBC: 'Torfaen County Borough Council'
    KGN: 'London Borough of Kingston'
    RMD: 'London Borough of Richmond'
    WAD: 'London Borough of Wandsworth'
    GRW: 'Royal Borough of Greenwich'
    TOR: 'Torbay Council'
    PLY: 'Plymouth City Council'
    BRA: 'City of Bradford Metropolitan District Council'
    CAL: 'Calderdale MBC'
    RBC: 'Rochdale Borough Council'
    SAL: 'Salford City Council'
    ESX: 'East Sussex County Council'
    HAF: 'London Borough of Hammersmith and Fulham'
    REC: 'Redcar & Cleveland Borough Council'
    NTHW: 'West Northamptonshire Council'
    NTHN: 'North Northamptonshire Council'
    LAM: 'London Borough of Lambeth'
    ISL: 'London Borough of Islington'
    CDN: 'London Borough of Camden'
    LEW: 'London Borough of Lewisham'
    BNT: 'London Borough of Barnet'
    HLW: 'London Borough of Hounslow'
    WSX: 'West Sussex County Council'
    BAD: 'London Borough of Barking and Dagenham'
    ENF: 'London Borough of Enfield'
    WAF: 'London Borough of Waltham Forest'
    CRY: 'London Borough of Croydon'
    RED: 'London Borough of Redbridge'
    HAR: 'London Borough of Haringey'
    EAL: 'London Borough of Ealing'
    BEX: 'London Borough of Bexley'
    BUR: 'Bury Metropolitan Borough Council'
    ESS: 'Essex County Council'
    HAC: 'London Borough of Hackney'
    COL: 'City of London Corporation'
    HAV: 'London Borough of Havering'
    NEW: 'London Borough of Newham'
    RTL: 'Rutland County Council'
    STCC: 'Stoke on Trent County Council'
    SSCC: 'Staffordshire County Council'
    LCC: 'Leicester City Council'
    LSCC: 'Lincolnshire County Council'
    NCC: 'Nottingham City Council'
    NSCC: 'Nottinghamshire County Council'
    DCC: 'Derby City Council'
    DCOC: 'Derby County Council'
    CCC: 'Coventry County Council'
    WCC: 'Warwickshire County Council'
    BCCO: 'Birmingham city council'
    SMBC: 'Solihull MBC'
    WSCC: 'Worcestershire County Council'
    HSCC: 'Herefordshire County Council'
    DMBC: 'Dudley MBC'
    PCCL: 'Portsmouth City Council'
    SCC: 'Southampton City Council'
    WSC: 'Wiltshire Council'
    SBCO: 'Swindon Borough Council'
    SCCO: 'Somerset County Council'
    BCPC: 'Bournemouth, Christchurch & Poole council (BCP)'
    DCCO: 'Dorset County Council'
    LBH: 'London Borough Hillingdon'
    RBK: 'Royal Borough of Kingston'
    LBKT: 'London Borough Kingston upon Thames'
    LBS: 'London Borough of slough'
    COLO: 'City of London'
    LBSM: 'London Borough of Sutton & Merton'
    RBCO: 'Reading Borough Council'
    SBOC: 'Slough Borough Council'
    WBCO: 'Wokinghm Borough Council'
    OSCC: 'Oxfordshire County Council'
    TBCO: 'Thurrock Borough Council'
    SOSBC: 'Southend-on-Sea Borough Council'
    HSCCO: 'Hertfordshire County Council'
    RCC: 'Rutland City Council'
    CCCO: 'Cambridge County Council'
    MEDC: 'Medway Council'
    MKC: 'Milton Keynes Council'
    BSCC: 'Buckinghamshire County Council'
    KUHCC: 'Kingston Upon Hull CC'
    ERY: 'East Riding Yorkshire C'
    NLSC: 'North Lincolnshire C'
    NELS: 'North East Lincolnshire'
    NCCC: 'Newcastle CC'
    STMBC: 'South Tyneside MBC'
    DBC: 'Darlington BC'
    DURCC: 'Durham CC'
    MBC: 'Middlesbrough BC'
    STBC: 'Stockton BC'
    WAK: 'Wakefield'
    LIV: 'Liverpool'
    KNO: 'Knowsley'
    CHE: 'Chesire East'
    CNW: 'Crewe & Nantwich'
    LSCCO: 'Lancashire County Council'
    BDBC: 'Blackburn with Darwen Borough Council'
    OLD: 'Oldham'
    STO: 'Stockport'
    TAM: 'Tameside'
    SWCC: 'Swansea CC'
    CER: 'Ceredigion'
    CARC: 'Cardiff Council'
    MTC: 'Merthyr Tydfil Council'
    SEWAS: 'South East Wales Adoption Service'
    RCT: 'Rhondda Cynon Taff'
    CYG: 'Cyngor Gwynedd'
    CSYM: 'Cyngor Sir Ynys Mon'
    GWC: 'Gwynedd Council'
